### ISSUE TITLE
Foreign Objects in SVG are not converted

### ISSUE THREAD

**Issue by viknesb** [canvg/canvg#369] opened 2015-06-13 18:08 UTC
If I have a HTML snippet within a Foreign Object tag inside my SVG, it is not drawn in the canvas. But it does seem that it is possible to draw HTML in a Canvas as described here.
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas
Would be really nice to have this feature.

**Comment by gabelerner** [comment] 2015-06-20 20:18
the example seems to be drawing a full svg inside a canvas, which if your browser supports, then you don't need this library right?

**Comment by viknesb** [comment] 2015-06-24 17:52
I though you are building on top of what is given in the example to render the canvas. With the way given in the example, other objects in my SVG are not converted.

**Comment by gabelerner** [comment] 2015-07-18 17:51
the point of this library is for devices that don't have svg capability but do have canvas capability (HTML5).  the link you posted suggests that the browser does have svg capability, which means you can just use the browser to render svgs in canvas instead of canvg.

**Comment by maciejjankowski** [comment] 2015-07-31 20:46
Hello @gabelerner ! first, thanks for building this! It is superuseful

I don't know if my issue is similar to this one, or not but I have a svg base image composed of couple texts and boxes, on which I am overlaying another svg image `<image href="my.svg"` now the problem is that this `<image>` does not render with the same dimensions (it is very small) as on the resulting svg:

![image](https://cloud.githubusercontent.com/assets/2905995/9017114/f4c9ede6-37d5-11e5-89ec-73ac8c90a58d.png)

**Comment by gabelerner** [comment] 2018-12-29 23:52
moving to https://github.com/canvg/canvg/issues/671

**Closed by gabelerner** 2018-12-29 23:52 UTC
