### ISSUE TITLE
Using canvg in React project gives a compile error

### ISSUE THREAD

**Issue by vijayst** [canvg/canvg#583] opened 2018-06-23 13:03 UTC
I am using canvg in a React project. 

```
yarn add canvg
import canvg from 'canvg';
```

It gives a compile error.

> ERROR in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
> Module not found: Error: Can't resolve 'child_process' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/lib/jsdom/living'
>  @ ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js 4:18-42
>  @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/cssstyle/lib/CSSStyleDeclaration.js
> Module not found: Error: Can't resolve 'fs' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/cssstyle/lib'
>  @ ./node_modules/cssstyle/lib/CSSStyleDeclaration.js 7:9-22
>  @ ./node_modules/jsdom/lib/jsdom/level2/style.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/lib/jsdom.js
> Module not found: Error: Can't resolve 'fs' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/lib'
>  @ ./node_modules/jsdom/lib/jsdom.js 6:11-24
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
> Module not found: Error: Can't resolve 'fs' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/lib/jsdom/browser'
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js 7:11-24
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/lib/jsdom/living/xhr-utils.js
> Module not found: Error: Can't resolve 'fs' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/lib/jsdom/living'
>  @ ./node_modules/jsdom/lib/jsdom/living/xhr-utils.js 5:11-24
>  @ ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/node_modules/request/lib/har.js
> Module not found: Error: Can't resolve 'fs' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/node_modules/request/lib'
>  @ ./node_modules/jsdom/node_modules/request/lib/har.js 3:9-22
>  @ ./node_modules/jsdom/node_modules/request/request.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'net' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/forever-agent'
>  @ ./node_modules/forever-agent/index.js 6:10-24
>  @ ./node_modules/jsdom/node_modules/request/request.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/node_modules/request/node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/lib'
>  @ ./node_modules/jsdom/node_modules/request/node_modules/tough-cookie/lib/cookie.js 32:10-24
>  @ ./node_modules/jsdom/node_modules/request/lib/cookies.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/jsdom/node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/jsdom/node_modules/tough-cookie/lib'
>  @ ./node_modules/jsdom/node_modules/tough-cookie/lib/cookie.js 32:10-24
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'net' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/tunnel-agent'
>  @ ./node_modules/tunnel-agent/index.js 3:10-24
>  @ ./node_modules/jsdom/node_modules/request/lib/tunnel.js
>  @ ./node_modules/jsdom/node_modules/request/request.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'tls' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/forever-agent'
>  @ ./node_modules/forever-agent/index.js 7:10-24
>  @ ./node_modules/jsdom/node_modules/request/request.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js
> 
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'tls' in '/Users/vijayst/Documents/react/dandi/dandi-ui/node_modules/tunnel-agent'
>  @ ./node_modules/tunnel-agent/index.js 4:10-24
>  @ ./node_modules/jsdom/node_modules/request/lib/tunnel.js
>  @ ./node_modules/jsdom/node_modules/request/request.js
>  @ ./node_modules/jsdom/node_modules/request/index.js
>  @ ./node_modules/jsdom/lib/jsdom/browser/resource-loader.js
>  @ ./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js
>  @ ./node_modules/jsdom/lib/jsdom/living/node-iterator.js
>  @ ./node_modules/jsdom/lib/jsdom/living/index.js
>  @ ./node_modules/jsdom/lib/jsdom.js
>  @ ./node_modules/canvg/canvg.js
>  @ ./src/reports/SummaryWidget.js
>  @ ./src/comp/Summary.js
>  @ ./src/layout/Routes.js
>  @ ./src/Main.js
>  @ ./src/App.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack/hot/only-dev-server ./src/App.js

**Comment by mistic100** [comment] 2018-07-03 13:16
The problem is this line which is false inside Webpack.
https://github.com/canvg/canvg/blob/master/canvg.js#L26

**Comment by mistic100** [comment] 2018-07-06 06:59
To solve this there are two things to do :

- change how the lib detects Node.js => https://github.com/canvg/canvg/pull/585
- ignore the two dependencies not needed in the browser => 
```js
new webpack.IgnorePlugin(/(jsdom|xmldom)/)
```

**Comment by endday** [comment] 2018-07-19 10:49
Maybe my experience can help other people.
I try your pull request #585 
my webpack version is "webpack": "^3.11.0"
but I still hava the problem like bug #583
I try to use your suggestion, use 
```
new webpack.IgnorePlugin(/(jsdom|xmldom)/)
```
it works
I think it maybe webpack and jsdom has some conflict

https://github.com/zinserjan/mocha-webpack/issues/6#issuecomment-213957809

I have an idea from this issue, then I use the externals in webpack.config.js
```
externals: {
    jsdom: 'require("jsdom")'
}
```
it also works success too

The author of jsdom said that jsdom does not support webpack, which is really frustrating.

**Comment by Pauan** [comment] 2018-08-05 14:50
This is not a runtime error, it is an error *while Webpack is bundling the code*. It happens because `canvg` has `jsdom` and `xmldom` dependencies (in `package.json`) but those dependencies cause Webpack to break.

The correct solution is for `canvg` to change its `package.json` and [add a `browser` property](https://github.com/defunctzombie/package-browser-field-spec) which lets Webpack know that `jsdom` and `xmldom` should not be loaded in the browser:

```json
{
    "browser": {
        "jsdom": false,
        "xmldom": false
    }
}
```

This is [used by `fabric`](https://github.com/fabricjs/fabric.js/blob/74fa4f1f30c5cc7a9a2a6eaab6af77aef54ef21c/package.json#L23-L33) (and many other npm packages).

**Comment by Pauan** [comment] 2018-08-10 21:30
This seems to be fixed by https://github.com/canvg/canvg/pull/591

**Comment by gabelerner** [comment] 2018-08-10 21:33
yup, it should be, please reopen if not

**Closed by gabelerner** 2018-08-10 21:33 UTC

**Comment by DiyarS** [comment] 2018-11-05 11:38
Hi! I'm getting similar errors, but only two this time with canvg@1.5.4 and webpack 3.1.0. I use React Boilerplate. Could anyone tell me how to fix this or is it possible to update versions on cdn so that I could import a script? Here are the errors that I get:

> ERROR in ./node_modules/canvas/lib/canvas.js
Module not found: Error: Can't resolve 'fs' in '/Users/userme/Desktop/Work projects/some_folder/some_project/node_modules/canvas/lib'
 @ ./node_modules/canvas/lib/canvas.js 22:9-22
 @ ./node_modules/canvg/dist/browser/canvg.min.js
 @ ./src/components/ImageAnnotation/index.js
 @ ./src/components/App.js
 @ ./src/components/Root.js
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

> ERROR in ./node_modules/canvas/build/Release/canvas.node
Module parse failed: /Users/userme/Desktop/Work projects/some_folder/some_project/node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/canvas/lib/bindings.js 3:17-56
 @ ./node_modules/canvas/lib/canvas.js
 @ ./node_modules/canvg/dist/browser/canvg.min.js
 @ ./src/components/ImageAnnotation/index.js
 @ ./src/components/App.js
 @ ./src/components/Root.js
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

**Comment by DiyarS** [comment] 2018-11-05 11:40
> yup, it should be, please reopen if not

Hi! I'm getting similar errors, but only two this time with canvg@1.5.4 and webpack 3.1.0. I use React Boilerplate. Could anyone tell me how to fix this or is it possible to update versions on cdn so that I could import a script? Here are the errors that I get:

> ERROR in ./node_modules/canvas/lib/canvas.js
Module not found: Error: Can't resolve 'fs' in '/Users/userme/Desktop/Work projects/some_folder/some_project/node_modules/canvas/lib'
 @ ./node_modules/canvas/lib/canvas.js 22:9-22
 @ ./node_modules/canvg/dist/browser/canvg.min.js
 @ ./src/components/ImageAnnotation/index.js
 @ ./src/components/App.js
 @ ./src/components/Root.js
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

> ERROR in ./node_modules/canvas/build/Release/canvas.node
Module parse failed: /Users/userme/Desktop/Work projects/some_folder/some_project/node_modules/canvas/build/Release/canvas.node Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/canvas/lib/bindings.js 3:17-56
 @ ./node_modules/canvas/lib/canvas.js
 @ ./node_modules/canvg/dist/browser/canvg.min.js
 @ ./src/components/ImageAnnotation/index.js
 @ ./src/components/App.js
 @ ./src/components/Root.js
 @ ./src/index.js
 @ multi ./src/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./src/index.js

**Comment by gabelerner** [comment] 2018-11-05 15:01
That's related to https://github.com/canvg/canvg/issues/647, I unpublished
